In [1]:
# Assignment No: 1
# Name: KSHITIJ NANDKUMAR WALKE
# Roll No: 37068
# Batch: D
# Title: Facebook Data Operations
# Problem Statement: Perform subset, merge, sort, transpose, reshape operations

In [2]:
import pandas as pd

df = pd.read_csv("Dataset_Facebook.csv")

In [3]:
df.head()

  Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions
0  139441;Photo;2;12;4;3;0;2752;5091;178;109;159;...
1  139441;Status;2;12;3;10;0;10460;19057;1457;136...
2  139441;Photo;3;12;3;3;0;2413;4373;177;113;154;...
3  139441;Photo;2;12;2;10;1;50128;87991;2211;790;...
4  139441;Photo;2;12;2;3;0;7244;13594;671;410;580...

In [4]:
df.columns

Index(['Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions'], dtype='object')

In [5]:
import pandas as pd

df = pd.read_csv("Dataset_Facebook.csv", sep=';')
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [6]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [7]:
subset = df[['Page total likes', 'Type']]
subset.head()

   Page total likes    Type
0            139441   Photo
1            139441  Status
2            139441   Photo
3            139441   Photo
4            139441   Photo

In [8]:
subset = df[['Page total likes', 'Type']]
subset.head()

   Page total likes    Type
0            139441   Photo
1            139441  Status
2            139441   Photo
3            139441   Photo
4            139441   Photo

In [9]:
df.head().T

,0,1,2,3,4
Page total likes,139441,139441,139441,139441,139441
Type,Photo,Status,Photo,Photo,Photo
Category,2,2,3,2,2
Post Month,12,12,12,12,12
Post Weekday,4,3,3,2,2
Post Hour,3,10,3,10,3
Paid,0.0,0.0,0.0,1.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244
Lifetime Post Total Impressions,5091,19057,4373,87991,13594
Lifetime Engaged Users,178,1457,177,2211,671
Lifetime Post Consumers,109,1361,113,790,410
Lifetime Post Consumptions,159,1674,154,1119,580
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396
comment,4,5,0,58,19
like,79.0,130.0,66.0,1572.0,325.0
share,17.0,29.0,14.0,147.0,49.0
Total Interactions,100,164,80,1777,393

In [10]:
df.shape

(500, 19)

In [11]:
df2 = df[['Type', 'Post Month']]
pd.merge(df, df2, on='Type').head()

,Page total likes,Type,Category,Post Month_x,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions,Post Month_y
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100,12
1,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100,12
2,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100,12
3,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100,12
4,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100,12

In [12]:
pd.melt(df, id_vars=['Type'])

        Type            variable     value
0      Photo    Page total likes  139441.0
1     Status    Page total likes  139441.0
2      Photo    Page total likes  139441.0
3      Photo    Page total likes  139441.0
4      Photo    Page total likes  139441.0
...      ...                 ...       ...
8995   Photo  Total Interactions      84.0
8996   Photo  Total Interactions      75.0
8997   Photo  Total Interactions     115.0
8998   Photo  Total Interactions     136.0
8999   Photo  Total Interactions     119.0

[9000 rows x 3 columns]